/*
 * File: types.c
 * Project: logger
 * Created: 2019-04-20
 * Author: Anton Ihonen, anton.ihonen@gmail.com
 *
 */

#include "types.h"

const LOG_LEVEL VALID_LOG_LEVELS[6] =
	{ L_TRACE, L_DEBUG, L_INFO, L_WARNING, L_ERROR, L_CRITICAL };

const char* const LOG_LEVEL_STRS[__VALID_LVL_COUNT] =
	{ "TRACE", "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL" };

const LOG_FILE_POLICY VALID_FILE_POLICIES[__VALID_FILEPOL_COUNT] =
	{ REWRITE, ROTATE, IGNORE_EXCESS };

const LOG_BUFFERING_POLICY VALID_BUF_POLICIES[__VALID_BUFPOL_COUNT] =
	{ NO_BUFFERING, LINE_BUFFERING, FULL_BUFFERING };
